### ISSUE TITLE
Page Pagination on mobile device not visible

### ISSUE THREAD

**Issue by Kurbm** [baoagency/polaris_view_components#441]
Hey,

Just seen, that the Page pagination arrows / buttons are not visible on mobile devices. 

Is this on purpose or a workaround available?

Best,
Kurbm

**Comment by kirillplatonov** [comment]
This seems to be an intentional design decision by Polaris. You can override it with custom CSS:
```css
.Polaris-Page-Header__PaginationWrapper {
  display: block !important;
}
```
